name: StatChat
options:
  bundleIdPrefix: com.statchat
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

targets:
  StatChat:
    type: application
    platform: iOS
    sources:
      - path: BaseballStatsEngine
        excludes:
          - "Resources/**"
      - path: BaseballStatsEngine/Resources/baseball_stats.db
        buildPhase: resources
      - path: BaseballStatsEngine/Resources/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.statchat.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 2
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        PRODUCT_NAME: StatChat
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
